// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccuxBVO-1kywUasvjb1XBv8sDWfahFvU',
    appId: '1:623352522134:web:4bd62d393eb37d2a1da9b7',
    messagingSenderId: '623352522134',
    projectId: 'nova-kaan-ayaz',
    authDomain: 'nova-kaan-ayaz.firebaseapp.com',
    storageBucket: 'nova-kaan-ayaz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQHhXhruP5npm_mdZ44Qo4CDi_5gNF_4',
    appId: '1:623352522134:android:59724e19bc917f051da9b7',
    messagingSenderId: '623352522134',
    projectId: 'nova-kaan-ayaz',
    storageBucket: 'nova-kaan-ayaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tS_OAP5V5QbsDfrCrpxCJuc39yexfMI',
    appId: '1:623352522134:ios:107b8c22b6384cab1da9b7',
    messagingSenderId: '623352522134',
    projectId: 'nova-kaan-ayaz',
    storageBucket: 'nova-kaan-ayaz.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAccuxBVO-1kywUasvjb1XBv8sDWfahFvU',
    appId: '1:623352522134:web:9752e1c59c9291e01da9b7',
    messagingSenderId: '623352522134',
    projectId: 'nova-kaan-ayaz',
    authDomain: 'nova-kaan-ayaz.firebaseapp.com',
    storageBucket: 'nova-kaan-ayaz.firebasestorage.app',
  );

}